// Generated by scripts/gen-manifest.mjs — do not edit.
import type { Component } from 'vue'
import AddCircleIcon from 'hugeicons-animated-vue/icons/add-circle.vue'
import AirplaneTakeOff01Icon from 'hugeicons-animated-vue/icons/airplane-take-off-01.vue'
import AlarmClockIcon from 'hugeicons-animated-vue/icons/alarm-clock.vue'
import AlertCircleIcon from 'hugeicons-animated-vue/icons/alert-circle.vue'
import Archive02Icon from 'hugeicons-animated-vue/icons/archive-02.vue'
import ArrowDown02Icon from 'hugeicons-animated-vue/icons/arrow-down-02.vue'
import ArrowDownLeft01Icon from 'hugeicons-animated-vue/icons/arrow-down-left-01.vue'
import ArrowDownRight01Icon from 'hugeicons-animated-vue/icons/arrow-down-right-01.vue'
import ArrowLeft02Icon from 'hugeicons-animated-vue/icons/arrow-left-02.vue'
import ArrowRight02Icon from 'hugeicons-animated-vue/icons/arrow-right-02.vue'
import ArrowUp02Icon from 'hugeicons-animated-vue/icons/arrow-up-02.vue'
import ArrowUpLeft01Icon from 'hugeicons-animated-vue/icons/arrow-up-left-01.vue'
import ArrowUpRight01Icon from 'hugeicons-animated-vue/icons/arrow-up-right-01.vue'
import AttachmentIcon from 'hugeicons-animated-vue/icons/attachment.vue'
import BatteryCharging01Icon from 'hugeicons-animated-vue/icons/battery-charging-01.vue'
import BluetoothIcon from 'hugeicons-animated-vue/icons/bluetooth.vue'
import Bookmark01Icon from 'hugeicons-animated-vue/icons/bookmark-01.vue'
import Bug01Icon from 'hugeicons-animated-vue/icons/bug-01.vue'
import BulbIcon from 'hugeicons-animated-vue/icons/bulb.vue'
import Calendar03Icon from 'hugeicons-animated-vue/icons/calendar-03.vue'
import CalendarAdd01Icon from 'hugeicons-animated-vue/icons/calendar-add-01.vue'
import Call02Icon from 'hugeicons-animated-vue/icons/call-02.vue'
import CallIncoming01Icon from 'hugeicons-animated-vue/icons/call-incoming-01.vue'
import CallOutgoing01Icon from 'hugeicons-animated-vue/icons/call-outgoing-01.vue'
import Camera01Icon from 'hugeicons-animated-vue/icons/camera-01.vue'
import Cancel01Icon from 'hugeicons-animated-vue/icons/cancel-01.vue'
import ChevronDownIcon from 'hugeicons-animated-vue/icons/chevron-down.vue'
import ChevronLeftIcon from 'hugeicons-animated-vue/icons/chevron-left.vue'
import ChevronRightIcon from 'hugeicons-animated-vue/icons/chevron-right.vue'
import ChevronUpIcon from 'hugeicons-animated-vue/icons/chevron-up.vue'
import CircleCheckIcon from 'hugeicons-animated-vue/icons/circle-check.vue'
import CircleXIcon from 'hugeicons-animated-vue/icons/circle-x.vue'
import ClipboardPasteIcon from 'hugeicons-animated-vue/icons/clipboard-paste.vue'
import ClipboardIcon from 'hugeicons-animated-vue/icons/clipboard.vue'
import Clock01Icon from 'hugeicons-animated-vue/icons/clock-01.vue'
import CloudDownloadIcon from 'hugeicons-animated-vue/icons/cloud-download.vue'
import CloudLightningIcon from 'hugeicons-animated-vue/icons/cloud-lightning.vue'
import CloudRainIcon from 'hugeicons-animated-vue/icons/cloud-rain.vue'
import CloudUploadIcon from 'hugeicons-animated-vue/icons/cloud-upload.vue'
import CloudIcon from 'hugeicons-animated-vue/icons/cloud.vue'
import CodeXmlIcon from 'hugeicons-animated-vue/icons/code-xml.vue'
import Coffee02Icon from 'hugeicons-animated-vue/icons/coffee-02.vue'
import CommandIcon from 'hugeicons-animated-vue/icons/command.vue'
import CompassIcon from 'hugeicons-animated-vue/icons/compass.vue'
import Copy01Icon from 'hugeicons-animated-vue/icons/copy-01.vue'
import CreditCardIcon from 'hugeicons-animated-vue/icons/credit-card.vue'
import CrownIcon from 'hugeicons-animated-vue/icons/crown.vue'
import CursorPointer01Icon from 'hugeicons-animated-vue/icons/cursor-pointer-01.vue'
import DashboardSquare01Icon from 'hugeicons-animated-vue/icons/dashboard-square-01.vue'
import DatabaseIcon from 'hugeicons-animated-vue/icons/database.vue'
import Delete02Icon from 'hugeicons-animated-vue/icons/delete-02.vue'
import Diamond02Icon from 'hugeicons-animated-vue/icons/diamond-02.vue'
import DocumentAttachmentIcon from 'hugeicons-animated-vue/icons/document-attachment.vue'
import Download01Icon from 'hugeicons-animated-vue/icons/download-01.vue'
import EarthIcon from 'hugeicons-animated-vue/icons/earth.vue'
import Edit02Icon from 'hugeicons-animated-vue/icons/edit-02.vue'
import ExternalLinkIcon from 'hugeicons-animated-vue/icons/external-link.vue'
import EyeOffIcon from 'hugeicons-animated-vue/icons/eye-off.vue'
import EyeIcon from 'hugeicons-animated-vue/icons/eye.vue'
import FavouriteIcon from 'hugeicons-animated-vue/icons/favourite.vue'
import File01Icon from 'hugeicons-animated-vue/icons/file-01.vue'
import FileAddIcon from 'hugeicons-animated-vue/icons/file-add.vue'
import FileDownloadIcon from 'hugeicons-animated-vue/icons/file-download.vue'
import FileUploadIcon from 'hugeicons-animated-vue/icons/file-upload.vue'
import FilterIcon from 'hugeicons-animated-vue/icons/filter.vue'
import FireIcon from 'hugeicons-animated-vue/icons/fire.vue'
import FlashIcon from 'hugeicons-animated-vue/icons/flash.vue'
import FlowerIcon from 'hugeicons-animated-vue/icons/flower.vue'
import Folder01Icon from 'hugeicons-animated-vue/icons/folder-01.vue'
import FolderAddIcon from 'hugeicons-animated-vue/icons/folder-add.vue'
import FolderOpenIcon from 'hugeicons-animated-vue/icons/folder-open.vue'
import FullScreenIcon from 'hugeicons-animated-vue/icons/full-screen.vue'
import GhostIcon from 'hugeicons-animated-vue/icons/ghost.vue'
import GiftIcon from 'hugeicons-animated-vue/icons/gift.vue'
import GithubIcon from 'hugeicons-animated-vue/icons/github.vue'
import GridViewIcon from 'hugeicons-animated-vue/icons/grid-view.vue'
import HeadphoneOffIcon from 'hugeicons-animated-vue/icons/headphone-off.vue'
import HeadphonesIcon from 'hugeicons-animated-vue/icons/headphones.vue'
import HelpCircleIcon from 'hugeicons-animated-vue/icons/help-circle.vue'
import HistoryIcon from 'hugeicons-animated-vue/icons/history.vue'
import Home01Icon from 'hugeicons-animated-vue/icons/home-01.vue'
import Image01Icon from 'hugeicons-animated-vue/icons/image-01.vue'
import InboxIcon from 'hugeicons-animated-vue/icons/inbox.vue'
import InformationCircleIcon from 'hugeicons-animated-vue/icons/information-circle.vue'
import Key01Icon from 'hugeicons-animated-vue/icons/key-01.vue'
import Leaf01Icon from 'hugeicons-animated-vue/icons/leaf-01.vue'
import Link01Icon from 'hugeicons-animated-vue/icons/link-01.vue'
import LinkSquare02Icon from 'hugeicons-animated-vue/icons/link-square-02.vue'
import ListViewIcon from 'hugeicons-animated-vue/icons/list-view.vue'
import Loading03Icon from 'hugeicons-animated-vue/icons/loading-03.vue'
import Location01Icon from 'hugeicons-animated-vue/icons/location-01.vue'
import LocationAdd01Icon from 'hugeicons-animated-vue/icons/location-add-01.vue'
import LockIcon from 'hugeicons-animated-vue/icons/lock.vue'
import Login01Icon from 'hugeicons-animated-vue/icons/login-01.vue'
import Logout01Icon from 'hugeicons-animated-vue/icons/logout-01.vue'
import MagicWand01Icon from 'hugeicons-animated-vue/icons/magic-wand-01.vue'
import Mail01Icon from 'hugeicons-animated-vue/icons/mail-01.vue'
import MailOpenIcon from 'hugeicons-animated-vue/icons/mail-open.vue'
import MaximizeScreenIcon from 'hugeicons-animated-vue/icons/maximize-screen.vue'
import Menu01Icon from 'hugeicons-animated-vue/icons/menu-01.vue'
import Message01Icon from 'hugeicons-animated-vue/icons/message-01.vue'
import MessageAdd01Icon from 'hugeicons-animated-vue/icons/message-add-01.vue'
import Mic01Icon from 'hugeicons-animated-vue/icons/mic-01.vue'
import MinimizeScreenIcon from 'hugeicons-animated-vue/icons/minimize-screen.vue'
import MinusSignCircleIcon from 'hugeicons-animated-vue/icons/minus-sign-circle.vue'
import MinusSignIcon from 'hugeicons-animated-vue/icons/minus-sign.vue'
import Moon02Icon from 'hugeicons-animated-vue/icons/moon-02.vue'
import MoreHorizontalIcon from 'hugeicons-animated-vue/icons/more-horizontal.vue'
import MoreVerticalIcon from 'hugeicons-animated-vue/icons/more-vertical.vue'
import MouseLeftClick01Icon from 'hugeicons-animated-vue/icons/mouse-left-click-01.vue'
import MusicNote01Icon from 'hugeicons-animated-vue/icons/music-note-01.vue'
import Notification03Icon from 'hugeicons-animated-vue/icons/notification-03.vue'
import NotificationOff01Icon from 'hugeicons-animated-vue/icons/notification-off-01.vue'
import PaintBrush02Icon from 'hugeicons-animated-vue/icons/paint-brush-02.vue'
import PanelLeftIcon from 'hugeicons-animated-vue/icons/panel-left.vue'
import PartyIcon from 'hugeicons-animated-vue/icons/party.vue'
import PauseIcon from 'hugeicons-animated-vue/icons/pause.vue'
import PinIcon from 'hugeicons-animated-vue/icons/pin.vue'
import PlayIcon from 'hugeicons-animated-vue/icons/play.vue'
import PlusSignIcon from 'hugeicons-animated-vue/icons/plus-sign.vue'
import PrinterIcon from 'hugeicons-animated-vue/icons/printer.vue'
import PuzzleIcon from 'hugeicons-animated-vue/icons/puzzle.vue'
import QrCode01Icon from 'hugeicons-animated-vue/icons/qr-code-01.vue'
import RedoIcon from 'hugeicons-animated-vue/icons/redo.vue'
import RefreshIcon from 'hugeicons-animated-vue/icons/refresh.vue'
import Robot01Icon from 'hugeicons-animated-vue/icons/robot-01.vue'
import Rocket01Icon from 'hugeicons-animated-vue/icons/rocket-01.vue'
import SaveIcon from 'hugeicons-animated-vue/icons/save.vue'
import Scissor01Icon from 'hugeicons-animated-vue/icons/scissor-01.vue'
import Search01Icon from 'hugeicons-animated-vue/icons/search-01.vue'
import SentIcon from 'hugeicons-animated-vue/icons/sent.vue'
import Settings01Icon from 'hugeicons-animated-vue/icons/settings-01.vue'
import Share08Icon from 'hugeicons-animated-vue/icons/share-08.vue'
import Shield02Icon from 'hugeicons-animated-vue/icons/shield-02.vue'
import ShoppingCart01Icon from 'hugeicons-animated-vue/icons/shopping-cart-01.vue'
import ShoppingCartAdd01Icon from 'hugeicons-animated-vue/icons/shopping-cart-add-01.vue'
import SleepingIcon from 'hugeicons-animated-vue/icons/sleeping.vue'
import SlidersHorizontalIcon from 'hugeicons-animated-vue/icons/sliders-horizontal.vue'
import SmileIcon from 'hugeicons-animated-vue/icons/smile.vue'
import SnowIcon from 'hugeicons-animated-vue/icons/snow.vue'
import SortByDown01Icon from 'hugeicons-animated-vue/icons/sort-by-down-01.vue'
import SortByUp01Icon from 'hugeicons-animated-vue/icons/sort-by-up-01.vue'
import SparklesIcon from 'hugeicons-animated-vue/icons/sparkles.vue'
import SquareLock01Icon from 'hugeicons-animated-vue/icons/square-lock-01.vue'
import StarIcon from 'hugeicons-animated-vue/icons/star.vue'
import Sun03Icon from 'hugeicons-animated-vue/icons/sun-03.vue'
import Target01Icon from 'hugeicons-animated-vue/icons/target-01.vue'
import ThumbsUpIcon from 'hugeicons-animated-vue/icons/thumbs-up.vue'
import Tick02Icon from 'hugeicons-animated-vue/icons/tick-02.vue'
import UmbrellaIcon from 'hugeicons-animated-vue/icons/umbrella.vue'
import UndoIcon from 'hugeicons-animated-vue/icons/undo.vue'
import Upload01Icon from 'hugeicons-animated-vue/icons/upload-01.vue'
import UserAdd01Icon from 'hugeicons-animated-vue/icons/user-add-01.vue'
import UserCheck01Icon from 'hugeicons-animated-vue/icons/user-check-01.vue'
import UserGroupIcon from 'hugeicons-animated-vue/icons/user-group.vue'
import UserMultiple02Icon from 'hugeicons-animated-vue/icons/user-multiple-02.vue'
import UserRemove01Icon from 'hugeicons-animated-vue/icons/user-remove-01.vue'
import UserIcon from 'hugeicons-animated-vue/icons/user.vue'
import Video01Icon from 'hugeicons-animated-vue/icons/video-01.vue'
import VolumeHighIcon from 'hugeicons-animated-vue/icons/volume-high.vue'
import VolumeMute01Icon from 'hugeicons-animated-vue/icons/volume-mute-01.vue'
import Wallet01Icon from 'hugeicons-animated-vue/icons/wallet-01.vue'
import Wifi01Icon from 'hugeicons-animated-vue/icons/wifi-01.vue'
import ZoomInAreaIcon from 'hugeicons-animated-vue/icons/zoom-in-area.vue'
import ZoomOutAreaIcon from 'hugeicons-animated-vue/icons/zoom-out-area.vue'

export type IconEntry = {
  name: string
  component: Component
}

export const ICON_LIST: IconEntry[] = [
  { name: 'add-circle', component: AddCircleIcon },
  { name: 'airplane-take-off-01', component: AirplaneTakeOff01Icon },
  { name: 'alarm-clock', component: AlarmClockIcon },
  { name: 'alert-circle', component: AlertCircleIcon },
  { name: 'archive-02', component: Archive02Icon },
  { name: 'arrow-down-02', component: ArrowDown02Icon },
  { name: 'arrow-down-left-01', component: ArrowDownLeft01Icon },
  { name: 'arrow-down-right-01', component: ArrowDownRight01Icon },
  { name: 'arrow-left-02', component: ArrowLeft02Icon },
  { name: 'arrow-right-02', component: ArrowRight02Icon },
  { name: 'arrow-up-02', component: ArrowUp02Icon },
  { name: 'arrow-up-left-01', component: ArrowUpLeft01Icon },
  { name: 'arrow-up-right-01', component: ArrowUpRight01Icon },
  { name: 'attachment', component: AttachmentIcon },
  { name: 'battery-charging-01', component: BatteryCharging01Icon },
  { name: 'bluetooth', component: BluetoothIcon },
  { name: 'bookmark-01', component: Bookmark01Icon },
  { name: 'bug-01', component: Bug01Icon },
  { name: 'bulb', component: BulbIcon },
  { name: 'calendar-03', component: Calendar03Icon },
  { name: 'calendar-add-01', component: CalendarAdd01Icon },
  { name: 'call-02', component: Call02Icon },
  { name: 'call-incoming-01', component: CallIncoming01Icon },
  { name: 'call-outgoing-01', component: CallOutgoing01Icon },
  { name: 'camera-01', component: Camera01Icon },
  { name: 'cancel-01', component: Cancel01Icon },
  { name: 'chevron-down', component: ChevronDownIcon },
  { name: 'chevron-left', component: ChevronLeftIcon },
  { name: 'chevron-right', component: ChevronRightIcon },
  { name: 'chevron-up', component: ChevronUpIcon },
  { name: 'circle-check', component: CircleCheckIcon },
  { name: 'circle-x', component: CircleXIcon },
  { name: 'clipboard-paste', component: ClipboardPasteIcon },
  { name: 'clipboard', component: ClipboardIcon },
  { name: 'clock-01', component: Clock01Icon },
  { name: 'cloud-download', component: CloudDownloadIcon },
  { name: 'cloud-lightning', component: CloudLightningIcon },
  { name: 'cloud-rain', component: CloudRainIcon },
  { name: 'cloud-upload', component: CloudUploadIcon },
  { name: 'cloud', component: CloudIcon },
  { name: 'code-xml', component: CodeXmlIcon },
  { name: 'coffee-02', component: Coffee02Icon },
  { name: 'command', component: CommandIcon },
  { name: 'compass', component: CompassIcon },
  { name: 'copy-01', component: Copy01Icon },
  { name: 'credit-card', component: CreditCardIcon },
  { name: 'crown', component: CrownIcon },
  { name: 'cursor-pointer-01', component: CursorPointer01Icon },
  { name: 'dashboard-square-01', component: DashboardSquare01Icon },
  { name: 'database', component: DatabaseIcon },
  { name: 'delete-02', component: Delete02Icon },
  { name: 'diamond-02', component: Diamond02Icon },
  { name: 'document-attachment', component: DocumentAttachmentIcon },
  { name: 'download-01', component: Download01Icon },
  { name: 'earth', component: EarthIcon },
  { name: 'edit-02', component: Edit02Icon },
  { name: 'external-link', component: ExternalLinkIcon },
  { name: 'eye-off', component: EyeOffIcon },
  { name: 'eye', component: EyeIcon },
  { name: 'favourite', component: FavouriteIcon },
  { name: 'file-01', component: File01Icon },
  { name: 'file-add', component: FileAddIcon },
  { name: 'file-download', component: FileDownloadIcon },
  { name: 'file-upload', component: FileUploadIcon },
  { name: 'filter', component: FilterIcon },
  { name: 'fire', component: FireIcon },
  { name: 'flash', component: FlashIcon },
  { name: 'flower', component: FlowerIcon },
  { name: 'folder-01', component: Folder01Icon },
  { name: 'folder-add', component: FolderAddIcon },
  { name: 'folder-open', component: FolderOpenIcon },
  { name: 'full-screen', component: FullScreenIcon },
  { name: 'ghost', component: GhostIcon },
  { name: 'gift', component: GiftIcon },
  { name: 'github', component: GithubIcon },
  { name: 'grid-view', component: GridViewIcon },
  { name: 'headphone-off', component: HeadphoneOffIcon },
  { name: 'headphones', component: HeadphonesIcon },
  { name: 'help-circle', component: HelpCircleIcon },
  { name: 'history', component: HistoryIcon },
  { name: 'home-01', component: Home01Icon },
  { name: 'image-01', component: Image01Icon },
  { name: 'inbox', component: InboxIcon },
  { name: 'information-circle', component: InformationCircleIcon },
  { name: 'key-01', component: Key01Icon },
  { name: 'leaf-01', component: Leaf01Icon },
  { name: 'link-01', component: Link01Icon },
  { name: 'link-square-02', component: LinkSquare02Icon },
  { name: 'list-view', component: ListViewIcon },
  { name: 'loading-03', component: Loading03Icon },
  { name: 'location-01', component: Location01Icon },
  { name: 'location-add-01', component: LocationAdd01Icon },
  { name: 'lock', component: LockIcon },
  { name: 'login-01', component: Login01Icon },
  { name: 'logout-01', component: Logout01Icon },
  { name: 'magic-wand-01', component: MagicWand01Icon },
  { name: 'mail-01', component: Mail01Icon },
  { name: 'mail-open', component: MailOpenIcon },
  { name: 'maximize-screen', component: MaximizeScreenIcon },
  { name: 'menu-01', component: Menu01Icon },
  { name: 'message-01', component: Message01Icon },
  { name: 'message-add-01', component: MessageAdd01Icon },
  { name: 'mic-01', component: Mic01Icon },
  { name: 'minimize-screen', component: MinimizeScreenIcon },
  { name: 'minus-sign-circle', component: MinusSignCircleIcon },
  { name: 'minus-sign', component: MinusSignIcon },
  { name: 'moon-02', component: Moon02Icon },
  { name: 'more-horizontal', component: MoreHorizontalIcon },
  { name: 'more-vertical', component: MoreVerticalIcon },
  { name: 'mouse-left-click-01', component: MouseLeftClick01Icon },
  { name: 'music-note-01', component: MusicNote01Icon },
  { name: 'notification-03', component: Notification03Icon },
  { name: 'notification-off-01', component: NotificationOff01Icon },
  { name: 'paint-brush-02', component: PaintBrush02Icon },
  { name: 'panel-left', component: PanelLeftIcon },
  { name: 'party', component: PartyIcon },
  { name: 'pause', component: PauseIcon },
  { name: 'pin', component: PinIcon },
  { name: 'play', component: PlayIcon },
  { name: 'plus-sign', component: PlusSignIcon },
  { name: 'printer', component: PrinterIcon },
  { name: 'puzzle', component: PuzzleIcon },
  { name: 'qr-code-01', component: QrCode01Icon },
  { name: 'redo', component: RedoIcon },
  { name: 'refresh', component: RefreshIcon },
  { name: 'robot-01', component: Robot01Icon },
  { name: 'rocket-01', component: Rocket01Icon },
  { name: 'save', component: SaveIcon },
  { name: 'scissor-01', component: Scissor01Icon },
  { name: 'search-01', component: Search01Icon },
  { name: 'sent', component: SentIcon },
  { name: 'settings-01', component: Settings01Icon },
  { name: 'share-08', component: Share08Icon },
  { name: 'shield-02', component: Shield02Icon },
  { name: 'shopping-cart-01', component: ShoppingCart01Icon },
  { name: 'shopping-cart-add-01', component: ShoppingCartAdd01Icon },
  { name: 'sleeping', component: SleepingIcon },
  { name: 'sliders-horizontal', component: SlidersHorizontalIcon },
  { name: 'smile', component: SmileIcon },
  { name: 'snow', component: SnowIcon },
  { name: 'sort-by-down-01', component: SortByDown01Icon },
  { name: 'sort-by-up-01', component: SortByUp01Icon },
  { name: 'sparkles', component: SparklesIcon },
  { name: 'square-lock-01', component: SquareLock01Icon },
  { name: 'star', component: StarIcon },
  { name: 'sun-03', component: Sun03Icon },
  { name: 'target-01', component: Target01Icon },
  { name: 'thumbs-up', component: ThumbsUpIcon },
  { name: 'tick-02', component: Tick02Icon },
  { name: 'umbrella', component: UmbrellaIcon },
  { name: 'undo', component: UndoIcon },
  { name: 'upload-01', component: Upload01Icon },
  { name: 'user-add-01', component: UserAdd01Icon },
  { name: 'user-check-01', component: UserCheck01Icon },
  { name: 'user-group', component: UserGroupIcon },
  { name: 'user-multiple-02', component: UserMultiple02Icon },
  { name: 'user-remove-01', component: UserRemove01Icon },
  { name: 'user', component: UserIcon },
  { name: 'video-01', component: Video01Icon },
  { name: 'volume-high', component: VolumeHighIcon },
  { name: 'volume-mute-01', component: VolumeMute01Icon },
  { name: 'wallet-01', component: Wallet01Icon },
  { name: 'wifi-01', component: Wifi01Icon },
  { name: 'zoom-in-area', component: ZoomInAreaIcon },
  { name: 'zoom-out-area', component: ZoomOutAreaIcon },
]
